export const QUOTE_AUDIO_UNLOCK_GUESSES = 3;
export const QUOTE_TWO_UNLOCK_GUESSES = 5;
export const QUOTE_THREE_UNLOCK_GUESSES = 7;
export const QUOTE_REGION_UNLOCK_GUESSES = 9;
export const ABILITY_KEY_HINT_UNLOCK_GUESSES = 3;
export const CLASSIC_QUOTE_CLUE_UNLOCK_GUESSES = 5;
export const CLASSIC_ABILITY_CLUE_UNLOCK_GUESSES = 10;
export const CLASSIC_SPLASH_CLUE_UNLOCK_GUESSES = 15;
